# -*- coding: utf-8 -*-
"""Childhood Anemia in Nigeria- v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14RVfPQf7GfLT5-bYdWdaoDMNadJfOhuX

# Childhood Anemia 🩸

# Set-up ⚙️

## Install necessary packages 📦
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install pycaret[full]
# !pip install tableone
# !pip install pysal
# !pip install autoviz
# !pip install ydata-profiling
# !pip install sweetviz
#

"""## Load packages 📂"""

# check installed version
import pandas as pd
import plotly.graph_objects as go
import numpy as np
import seaborn as sns
import geopandas as gpd
import matplotlib.pyplot as plt
from esda.moran import Moran_Local
from libpysal.weights import Queen
from tableone import TableOne
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.formula.api import mixedlm
import requests
import zipfile
import io
import os

from ydata_profiling import ProfileReport
import sweetviz as sv
from google.colab import files
import shap
import pycaret
import xgboost

"""## Download dataset 📥"""

!wget https://raw.githubusercontent.com/olaTechie/dhs_codes/master/tbm_data.csv

"""## Load and clean data 🧹



"""

df = pd.read_csv("./tbm_data.csv")
# Ensure 'anemic' is categorical
df['anemic'] = df['anemic'].astype('category')
df['anemic_numeric'] = (df['anemic'] == 'Anemic').astype(int)
df['anemic_binary'] = df['anemic'].apply(lambda x: 1 if x == 'Anemic' else 0)

# Modify urban variable
df['urban'] = df['urban'].map({1: 'Urban', 0: 'Rural'})

# Modify kid_male variable
df['kid_male'] = df['kid_male'].map({1: 'Male', 0: 'Female'})

# Modify mat_hinsur variable
df['mat_hinsur'] = df['mat_hinsur'].map({1: 'Yes', 0: 'No'})

# Modify mad variable
df['mad'] = df['mad'].map({1: 'Yes', 0: 'No'})

# Modify mat_fhead variable
df['mat_fhead'] = df['mat_fhead'].map({1: 'Yes', 0: 'No'})

# Modify mat_wealth variable
wealth_order = ['poorest', 'poorer', 'middle', 'richer', 'richest']
df['mat_wealth'] = pd.Categorical(df['mat_wealth'], categories=wealth_order, ordered=True)

# Sort the DataFrame by mat_wealth if needed
df = df.sort_values('mat_wealth')

rename_dict = {
    "mat_cage": "Mother Age",
    "mat_edu": "Mother Education",
    "mat_wealth": "Wealth Index",
    "urban": "Place of Residence",
    "media_access": "Media Access",
    "kid_male": "Sex of Children",
    "kid_cage": "Children Age",
    "kid_bord": "Birth Order",
    "kid_u5c": "Number of Under-5 Children",
    "mat_hinsur": "Health Insurance",
    "mat_fhead": "Female Headed Household",
    "money_problem": "Have Money Problem",
    "religion": "Religion",
    "ethnicity": "Ethnicity",
    "unsafewater": "Household Unsafe Water",
    "poor_sanitation": "Household Poor Sanitation",
    "hap": "Household Air Pollution",
    "zhser": "Maternal Health Seeking",
    "mad": "Minimum Acceptable Diet",
    "com_diversity": "Community Ethnic Diversity",
    "com_poverty": "Community Poverty Rate",
    "com_illit": "Community Illiteracy Rate",
    "com_uemp": "Community Unemployment Rate",
    "region": "Geographical Region",
    "all_population_count_2015": "All Population Count",
    "annual_precipitation_2015": "Annual Precipitation",
    "aridity_2015": "Aridity",
    "day_land_surface_temp_2015": "Day Land Surface Temperature",
    "diurnal_temperature_range_2015": "Diurnal Temperature Range",
    "proximity_to_water": "Proximity to Water",
    "drought_episodes": "Drought Episodes",
    "enhanced_vegetation_index_2015": "Enhanced Vegetation Index",
    "frost_days_2015": "Frost Days",
    "growing_season_length": "Growing Season Length",
    "livestock_cattle": "Livestock Cattle",
    "livestock_chickens": "Livestock Chickens",
    "livestock_ducks": "Livestock Ducks",
    "livestock_goats": "Livestock Goats",
    "livestock_pigs": "Livestock Pigs",
    "livestock_sheep": "Livestock Sheep",
    "maximum_temperature_2015": "Maximum Temperature",
    "mean_temperature_2015": "Mean Temperature",
    "night_land_surface_temp_2015": "Night Land Surface Temperature",
    "rainfall_2015": "Rainfall",
    "wet_days_2015": "Wet Days"
}

df.rename(columns=rename_dict, inplace=True)

# Descriptive statistics
all_vars = [
    "anemic",
    "Mother Age",
    "Mother Education",
    "Wealth Index",
    "Place of Residence",
    "Media Access",
    "Sex of Children",
    "Children Age",
    "Birth Order",
    "Number of Under-5 Children",
    "Health Insurance",
    "Female Headed Household",
    "Have Money Problem",
    "Religion",
    "Ethnicity",
    "Household Unsafe Water",
    "Household Poor Sanitation",
    "Household Air Pollution",
    "Maternal Health Seeking",
    "Minimum Acceptable Diet",
    "Geographical Region",
    "Community Ethnic Diversity",
    "Community Poverty Rate",
    "Community Illiteracy Rate",
    "Community Unemployment Rate",
    "All Population Count",
    "Annual Precipitation",
    "Aridity",
    "Day Land Surface Temperature",
    "Diurnal Temperature Range",
    "Proximity to Water",
    "Drought Episodes",
    "Enhanced Vegetation Index",
    "Frost Days",
    "Livestock Cattle",
    "Livestock Chickens",
    "Livestock Goats",
    "Livestock Pigs",
    "Livestock Sheep",
    "Maximum Temperature",
    "Mean Temperature",
    "Night Land Surface Temperature",
    "Rainfall",
    "Wet Days"
]

categorical_vars = [
    "anemic",
    "Mother Age",
    "Mother Education",
    "Wealth Index",
    "Place of Residence",
    "Media Access",
    "Sex of Children",
    "Children Age",
    "Birth Order",
    "Number of Under-5 Children",
    "Health Insurance",
    "Female Headed Household",
    "Have Money Problem",
    "Religion",
    "Ethnicity",
    "Household Unsafe Water",
    "Household Poor Sanitation",
    "Household Air Pollution",
    "Maternal Health Seeking",
    "Minimum Acceptable Diet",
    "Geographical Region",
    ]

df_eda =  df[all_vars]
df_eda.shape

"""# Exploratory Data Analyses 🔍

## Panda profiler 🐼
"""

# Create a ProfileReport
profile = ProfileReport(df_eda, title="Anemic Dataset Profile")

# # Display the report in the notebook
# profile.to_notebook_iframe()

# Save the report to an HTML file
profile.to_file("anemic_profile_report.html")

"""## Sweet visualizer 🍭"""

# Generate the report
report = sv.analyze(df_eda)

# Display the report in the notebook
report.show_notebook()

# Save the report to an HTML file
report.show_html("anemic_sweetviz_report.html")

"""## Table 1 - Descriptive statistics 📊"""

# Create TableOne
table1 = TableOne(df_eda, columns=all_vars, categorical=categorical_vars,
                  groupby='anemic', pval=True, htest_name=True)
print(table1.tabulate(tablefmt="fancy_grid"))

# Save to CSV
table1.to_csv("descriptive_statistics_table.csv")
# Save to HTML
table1.to_html("descriptive_statistics_table.html")

"""# Exploratory Spatial Analysis 🗺️"""

## Figure 1

# Group by state and aggregate
aggregated_data = df.groupby('state').agg({
    'anemic_numeric': 'sum',
    'anemic': 'count'
}).reset_index()

# Rename columns for clarity
aggregated_data.columns = ['state', 'event', 'number']
# Calculate prevalence
aggregated_data['prevalence'] = (aggregated_data['event'] / aggregated_data['number']) * 100
aggregated_data['state'] = aggregated_data['state'].str.title()

# aggregated_data

# Extract data
r = aggregated_data['event']
n = aggregated_data['number']
Name = aggregated_data['state']

# Calculate percentage unvaccinated
percentage_unvaccinated = (r / n) * 100

"""## State-level prevalence 📍"""

# Plotting
# Sort data by prevalence in decreasing order
aggregated_data = aggregated_data.sort_values(by='prevalence', ascending=False)
plt.figure(figsize=(12, 8))
sns.barplot(x='prevalence', y='state', data=aggregated_data, palette='viridis')
plt.xlabel('Prevalence of Anemia (%)')
plt.ylabel('State')
plt.title('Prevalence of Anemia by State in Nigeria')
plt.grid(True, axis='x', linestyle='--', alpha=0.7)

# Add the prevalence values on the bars
for index, value in enumerate(aggregated_data['prevalence']):
    plt.text(value, index, f'{value:.2f}%', va='center', ha='right', color='white')

"""## Map of prevalence 🗺️"""

# Load Nigeria shapefile
# Function to download and extract the shapefile
def download_gadm_shapefile(url, path):
    response = requests.get(url)
    with zipfile.ZipFile(io.BytesIO(response.content)) as z:
        z.extractall(path)

# URL to the GADM shapefile for Nigeria, level 1 (states)
url = 'https://geodata.ucdavis.edu/gadm/gadm4.1/shp/gadm41_NGA_shp.zip'
shapefile_path = 'gadm41_NGA_shp'

# Download and extract if not already done
if not os.path.exists(shapefile_path):
    os.makedirs(shapefile_path)
    download_gadm_shapefile(url, shapefile_path)

# Load the shapefile
gdf = gpd.read_file(os.path.join(shapefile_path, 'gadm41_NGA_1.shp'))

# # Display the unique values in the NAME_1 column
# unique_states = gdf['NAME_1'].unique()
# print("Unique states in the shapefile:")
# print(unique_states)

# unique_states_data = aggregated_data['state'].unique()
# print("Unique states in the data:")
# print(unique_states_data)

# Convert state names to lower case
gdf['state_lower'] = gdf['NAME_1'].replace({'Federal Capital Territory': 'Fct Abuja'})

# Merge the geodataframe with the prevalence data
gdf = gdf.merge(aggregated_data, how='left', left_on='state_lower', right_on='state')

# Plotting
fig, ax = plt.subplots(1, 1, figsize=(15, 10))
gdf.boundary.plot(ax=ax)
gdf.plot(column='prevalence', ax=ax, legend=True, cmap='OrRd',
         legend_kwds={'label': "Anemia Prevalence (%)",
                      'orientation': "horizontal"})

# Add state labels
for x, y, label in zip(gdf.geometry.centroid.x, gdf.geometry.centroid.y, gdf['NAME_1']):
    ax.text(x, y, label, fontsize=8, ha='center', color='black')

# Customize plot
ax.set_title('Prevalence of Anemia by State in Nigeria', fontdict={'fontsize': '15', 'fontweight' : '3'})
ax.axis('off')

# Save the plot
plt.savefig("anemia_prevalence_map.pdf")
plt.show()

"""## Funnel plot 🔄"""

# Create the funnel plot
fig = go.Figure()

# Add scatter plot for the data points
fig.add_trace(go.Scatter(
    x=n,
    y=percentage_unvaccinated,
    mode='markers+text',
    name='States',
    text=Name,
    textposition='top center',
    marker=dict(size=8, color='black'),
    textfont=dict(size=8, color='black')
))

# Calculate and add funnel lines
p = np.mean(r) / np.mean(n)
se = np.sqrt(p * (1 - p) / n)

fig.add_trace(go.Scatter(x=n, y=p * 100 + 2 * se * 100, mode='lines', name='95% CI', line=dict(color='blue', width=3, dash='dash')))
fig.add_trace(go.Scatter(x=n, y=p * 100 - 2 * se * 100, mode='lines', name='95% CI', line=dict(color='blue', width=3, dash='dash'), showlegend=False))
fig.add_trace(go.Scatter(x=n, y=p * 100 + 3 * se * 100, mode='lines', name='99.7% CI', line=dict(color='red', width=3, dash='dot')))
fig.add_trace(go.Scatter(x=n, y=p * 100 - 3 * se * 100, mode='lines', name='99.7% CI', line=dict(color='red', width=3, dash='dot'), showlegend=False))
fig.add_trace(go.Scatter(x=n, y=[p * 100] * len(n), mode='lines', name='Mean', line=dict(color='black', width=3)))


# Update layout
fig.update_layout(
    title='Funnel Plot',
    xaxis_title='Number of children aged 12-23 months',
    yaxis_title='Percentage Unvaccinated [for polio]',
    xaxis=dict(range=[0, 700]),
    legend=dict(x=800, y=0.99, bgcolor='rgba(255, 255, 255, 0.5)'),
    hovermode='closest'
)


# Show the plot
fig.show()

# To save as PDF (note: this requires the kaleido package)
fig.write_image("FunnelPlot.pdf")

"""## Hot- and cold-spot analyses 🔥❄️"""

# Calculate local Moran's I
w = Queen.from_dataframe(gdf)
w.transform = 'r'
moran_loc = Moran_Local(gdf['prevalence'], w)

# Add local Moran's I values and significance to the geodataframe
gdf['moran_local'] = moran_loc.Is
gdf['p_sim'] = moran_loc.p_sim
gdf['sig'] = moran_loc.p_sim < 0.05

# Define cluster types
gdf['cluster'] = 'Non-significant'
gdf.loc[(moran_loc.q == 1) & (gdf['sig']), 'cluster'] = 'High-High'  # High-High
gdf.loc[(moran_loc.q == 3) & (gdf['sig']), 'cluster'] = 'Low-Lo'  # Low-Low
gdf.loc[(moran_loc.q == 2) & (gdf['sig']), 'cluster'] = 'Low-High'  # Low-High
gdf.loc[(moran_loc.q == 4) & (gdf['sig']), 'cluster'] = 'High-Low'  # High-Low

# Plotting the clusters
fig, ax = plt.subplots(1, 1, figsize=(15, 10))
gdf.boundary.plot(ax=ax)
gdf.plot(column='cluster', ax=ax, legend=True,
         legend_kwds={'title': "Cluster Type"},
         cmap='Set1',
         categorical=True)

# Add state labels
for x, y, label in zip(gdf.geometry.centroid.x, gdf.geometry.centroid.y, gdf['NAME_1']):
    ax.text(x, y, label, fontsize=8, ha='center', color='black')

# Customize plot
ax.set_title("Local Moran's I Clusters for Anemia Prevalence by State in Nigeria", fontdict={'fontsize': '15', 'fontweight' : '3'})
ax.axis('off')

# Save the plot
plt.tight_layout()
plt.savefig("local_moran_anemia_prevalence_clusters_map.pdf")
plt.show()

